server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tuantruong2206/nab-icommerce-config-repo.git
          searchPaths: '{application}/{profile}'
          clone-on-start: true
          default-label: master

